name: backend_dart
description: SafeShell Backend - Dart/Shelf server.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  shelf: any
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
  dart_firebase_admin: any
  dart_jsonwebtoken: any
  dbcrypt: any
  dotenv: any
  crypto: ^3.0.3
  mime: any
  args: any
  http_parser: any
  uuid: any
  path: any
  googleapis_auth: any

dev_dependencies:
  http: ^1.6.0
  lints: any
  test: any
