org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError -Djavax.net.ssl.protocols=TLSv1.2
android.useAndroidX=true
org.gradle.daemon=true
kotlin.incremental=false
systemProp.http.connectionTimeout=600000
systemProp.http.socketTimeout=600000
systemProp.https.connectionTimeout=600000
systemProp.https.socketTimeout=600000
systemProp.https.protocols=TLSv1.2
systemProp.http.protocols=TLSv1.2
